{"trial_id": "0025", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "conv_blocks", "default": 1, "conditions": [], "min_value": 1, "max_value": 2, "step": 1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "filters_0", "default": 16, "conditions": [], "values": [16, 32, 64], "ordered": true}}, {"class_name": "Choice", "config": {"name": "kernel_size_0", "default": 3, "conditions": [], "values": [3], "ordered": true}}, {"class_name": "Choice", "config": {"name": "dense_units", "default": 32, "conditions": [], "values": [32, 64], "ordered": true}}, {"class_name": "Float", "config": {"name": "dropout", "default": 0.2, "conditions": [], "min_value": 0.2, "max_value": 0.4, "step": 0.1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.001, "conditions": [], "values": [0.001, 0.0001], "ordered": true}}, {"class_name": "Choice", "config": {"name": "filters_1", "default": 16, "conditions": [], "values": [16, 32, 64], "ordered": true}}, {"class_name": "Choice", "config": {"name": "kernel_size_1", "default": 3, "conditions": [], "values": [3], "ordered": true}}], "values": {"conv_blocks": 1, "filters_0": 32, "kernel_size_0": 3, "dense_units": 32, "dropout": 0.2, "learning_rate": 0.001, "filters_1": 32, "kernel_size_1": 3, "tuner/epochs": 10, "tuner/initial_epoch": 4, "tuner/bracket": 1, "tuner/round": 1, "tuner/trial_id": "0021"}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 53, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: Graph execution error:\n\nDetected at node PyFunc defined at (most recent call last):\n<stack traces unavailable>\nMemoryError: \nTraceback (most recent call last):\n\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\python\\ops\\script_ops.py\", line 269, in __call__\n    ret = func(*args)\n\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\python\\autograph\\impl\\api.py\", line 643, in wrapper\n    return func(*args, **kwargs)\n\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\python\\data\\ops\\from_generator_op.py\", line 198, in generator_py_func\n    values = next(generator_state.get_iterator(iterator_id))\n\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\trainers\\data_adapters\\py_dataset_adapter.py\", line 264, in _finite_generator\n    yield self._standardize_batch(self.py_dataset[i])\n\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\legacy\\preprocessing\\image.py\", line 68, in __getitem__\n    return self._get_batches_of_transformed_samples(index_array)\n\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\legacy\\preprocessing\\image.py\", line 313, in _get_batches_of_transformed_samples\n    img = image_utils.load_img(\n\n  File \"C:\\Users\\fiansyah\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\src\\utils\\image_utils.py\", line 292, in load_img\n    img = img.resize(width_height_tuple, resample)\n\n  File \"C:\\Users\\fiansyah\\AppData\\Roaming\\Python\\Python310\\site-packages\\PIL\\Image.py\", line 2336, in resize\n    self.load()\n\n  File \"C:\\Users\\fiansyah\\AppData\\Roaming\\Python\\Python310\\site-packages\\PIL\\ImageFile.py\", line 250, in load\n    self.load_prepare()\n\n  File \"C:\\Users\\fiansyah\\AppData\\Roaming\\Python\\Python310\\site-packages\\PIL\\ImageFile.py\", line 326, in load_prepare\n    self.im = Image.core.new(self.mode, self.size)\n\nMemoryError\n\n\n\t [[{{node PyFunc}}]]\n\t [[IteratorGetNext]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_multi_step_on_iterator_176832]\n"}